// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufrijlcihzjrlhxszmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZnJpamxjaWh6anJsaHhzem1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjMxMDEsImV4cCI6MjA2MTQ5OTEwMX0.UyWdy5cnxDDz4fmXa8kPvY-zCpKulB-tgwMcLOAS_IQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);